#!/bin/bash
#
# ci/scripts/create-release-and-deploy
#
# Script for generating Github release / tag assets
# and managing release notes for a BOSH Release pipeline
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

cat > ~/.bosh_config << EOF
---
aliases:
  target:
    bosh-lite: ${BOSH_LITE_TARGET}
auth:
  ${BOSH_LITE_TARGET}:
    username: ${BOSH_LITE_USERNAME}
    password: ${BOSH_LITE_PASSWORD}
EOF

set -ex
cd ${REPO_ROOT}
git submodule update --init --recursive --force

bosh target ${BOSH_LITE_TARGET}
bosh -n delete deployment ${BOSH_LITE_DEPLOYMENT} --force || echo "continuing on..."
bosh -n create release
bosh -n upload release --rebase || echo "Continuing..."
echo Generating warden-specific manifest
./templates/make_manifest warden 10.244.0.22
bosh -n deploy
