---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: ((haproxy-backend-port))
        backend_servers: ((haproxy-backend-servers))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-noble
    version: latest

releases:
- name: bpm
  version: 1.4.26
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.26
  sha1: sha256:40af85114d2a8a67812bf65212076581ea42cefcf67ee6b8d78d778ed1ca2b85
- name: haproxy
  version: 16.4.0+3.2.13
  url: https://github.com/cloudfoundry/haproxy-boshrelease/releases/download/v16.4.0+3.2.13/haproxy-16.4.0+3.2.13.tgz
  sha1: sha256:a6544aaab0de421ff7342c7511198c428bfb49e136b9279f2345585b53f8979b
