meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest
  instances:
    ha_proxy:
      public_z1:  (( merge || 1 ))
      public_z2:  (( merge || 0 ))
      private_z1: (( merge || 1 ))
      private_z2: (( merge || 0 ))


jobs:
  - name: public_haproxy_z1
    networks:
      - name: cf_haproxy1
    resource_pool: small_z1
    instances: (( meta.instances.ha_proxy.public_z1 ))
  - name: private_haproxy_z1
    network:
      - name: cf_haproxy1
    resource_pool: small_z1
    instances: (( meta.instances.ha_proxy.private_z1 ))
  - name: public_haproxy_z2
    networks:
      - name: cf_haproxy2
    resource_pool: small_z1
    instances: (( meta.instances.ha_proxy.public_z2 ))
  - name: private_haproxy_z2
    network:
      - name: cf_haproxy2
    resource_pool: small_z1
    instances: (( meta.instances.ha_proxy.private_z2 ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small
  - name: small_z2
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: cf_haproxy1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
  - name: cf_haproxy2
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
