---

groups:
  - name: haproxy-boshrelease
    jobs:
      - unit-tests
      - unit-tests-pr
      - acceptance-tests
      - acceptance-tests-pr
      - rc
      - shipit
      - patch
      - minor
      - major
      - autobump-dependencies
      - build-haproxy-testflight-image

jobs:
  - name: unit-tests
    public: true
    serial: true
    plan:
    - do:
      - get: git
        trigger: true
      - get: haproxy-boshrelease-testflight
      - task: lint
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git }
          caches:
          - path: git/vendor/cache
          - path: git/.bundle
          run:
            path: ./git/ci/scripts/lint
            args: []
          params:
            REPO_ROOT: git
      - task: unit-tests
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git }
          caches:
          - path: git/vendor/cache
          - path: git/.bundle
          run:
            path: ./git/ci/scripts/unit-tests
            args: []
          params:
            REPO_ROOT: git
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:     "((slack.fail_url)) haproxy-boshrelease : unit-tests job failed"

  - name: unit-tests-pr
    public: true
    serial: true
    plan:
    - do:
      - { get: git-pull-requests, trigger: true, version: every }
      - get: haproxy-boshrelease-testflight
      - put: git-pull-requests
        params:
          path: git-pull-requests
          status: pending
          context: unit-tests
      - task: lint
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git-pull-requests }
          caches:
          - path: git-pull-requests/vendor/cache
          - path: git-pull-requests/.bundle
          run:
            path: ./git-pull-requests/ci/scripts/lint
            args: []
          params:
            REPO_ROOT: git-pull-requests
      - task: unit-tests
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git-pull-requests }
          caches:
          - path: git-pull-requests/vendor/cache
          - path: git-pull-requests/.bundle
          run:
            path: ./git-pull-requests/ci/scripts/unit-tests
            args: []
          params:
            REPO_ROOT: git-pull-requests
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: success
        context: unit-tests
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
        context: unit-tests

  - name: acceptance-tests
    public: true
    serial: true
    plan:
    - do:
      - in_parallel:
        - { get: git, trigger: true, passed: [unit-tests] }
        - { get: stemcell }
        - { get: stemcell-bionic }
        - get: haproxy-boshrelease-testflight
      - task: acceptance-tests
        privileged: true
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git }
            - { name: stemcell }
            - { name: stemcell-bionic }
          run:
            path: ./git/ci/scripts/acceptance-tests
            args: []
          params:
            REPO_ROOT:            git
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:     "((slack.fail_url)) haproxy-boshrelease : acceptance tests failed"

  - name: acceptance-tests-pr
    public: true
    serial: true
    plan:
    - do:
      - { get: git-pull-requests, trigger: true, version: every }
      - { get: stemcell }
      - { get: stemcell-bionic }
      - get: haproxy-boshrelease-testflight
      - put: git-pull-requests
        params:
          path: git-pull-requests
          status: pending
          context: acceptance-tests
        get_params:
          list_changed_files: true
      - task: acceptance-tests
        privileged: true
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - { name: git-pull-requests }
            - { name: stemcell }
            - { name: stemcell-bionic }
          run:
            path: ./git-pull-requests/ci/scripts/acceptance-tests
            args: []
          params:
            REPO_ROOT:            git-pull-requests
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: success
        context: acceptance-tests
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
        context: acceptance-tests

  - name: rc
    public: true
    plan:
    - do:
      - in_parallel:
          - { get: git,     trigger: true,  passed: [acceptance-tests] }
          - { get: version, trigger: false, params: {pre: rc} }
      - put: version
        params: {file: version/number}
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:     "((slack.fail_url)) haproxy-boshrelease : rc job failed"

  - name: patch
    public: true
    plan:
      - do:
          - { get: version, trigger: false, params: {bump: patch} }
          - { put: version,                 params: {file: version/number} }
        on_failure:
          put: notify
          params:
            channel:  "#haproxy-boshrelease"
            username: ci-bot
            icon_url: "((slack.icon))"
            text:    "((slack.fail_url)) haproxy-boshrelease : patch job failed"

  - name: minor
    public: true
    plan:
    - do:
      - { get: version, trigger: false, params: {bump: minor} }
      - { put: version,                 params: {file: version/number} }
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:    "((slack.fail_url)) haproxy-boshrelease : minor job failed"

  - name: major
    public: true
    plan:
    - do:
      - { get: version, trigger: false, params: {bump: major} }
      - { put: version,                 params: {file: version/number} }
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:    "((slack.fail_url)) haproxy-boshrelease : major job failed"

  - name: shipit
    public: true
    serial: true
    plan:
    - do:
      - in_parallel:
          - { get: version, passed: [rc], params: {bump: final} }
          - { get: git,     passed: [rc] }
          - get: haproxy-boshrelease-testflight
      - task: release
        image: haproxy-boshrelease-testflight
        config:
          platform: linux
          inputs:
            - name: version
            - name: git
          outputs:
            - name: gh
            - name: pushme
            - name: notifications
          run:
            path: ./git/ci/scripts/shipit
            args: []
          params:
            REPO_ROOT:    git
            VERSION_FROM: version/number
            RELEASE_ROOT: gh
            REPO_OUT:     pushme
            NOTIFICATION_OUT: notifications
            BRANCH:        master
            GITHUB_OWNER:  cloudfoundry
            GIT_USER_NAME:  ((github.bot_user))
            GIT_USER_EMAIL: ((github.bot_email))
            GCP_SERVICE_KEY: ((gcp.service_key))
      - put: git
        params:
          rebase: true
          repository: pushme/git
      - put: blobstore
        params:
          file:  "gh/artifacts/haproxy-*.tgz"
      - put: github-release
        params:
          name:   gh/name
          tag:    gh/tag
          body:   gh/notes.md
          globs:  [gh/artifacts/*, gh/artifacts-patched/*]
      - put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text_file: notifications/message
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:     "((slack.fail_url)) haproxy-boshrelease : shipit job failed"

  - name: autobump-dependencies
    public: true
    serial: true
    plan:
      - do:
          - get: daily
            trigger: true
          - get: git
          - get: haproxy-boshrelease-testflight
          - task: autobump-dependencies
            image: haproxy-boshrelease-testflight
            config:
              inputs:
                - name: git
              platform: linux
              run:
                dir: git
                path: /usr/bin/python3
                args: ["ci/scripts/autobump-dependencies.py"]
              params:
                REPO_ROOT: git
                PR_BASE: master
                PR_ORG: cloudfoundry
                PR_LABEL: run-ci
                GCP_SERVICE_KEY: ((gcp.service_key))
                GITHUB_COM_TOKEN: ((github.access_token))

  - name: build-haproxy-testflight-image
    public: true
    serial: true
    plan:
      - in_parallel:
          - get: git-ci
            trigger: true
          - get: daily
            trigger: true
          - get: docker-cpi-image
            trigger: true
      - task: create-daily-tag
        image: docker-cpi-image
        config:
          outputs:
            - name: tag
          platform: linux
          run:
            path: sh
            args:
            - -exc
            - date +%Y.%m.%d-%H%M%S | tee tag/today
      - put: haproxy-boshrelease-testflight
        params:
          tag_as_latest: true
          tag_file: tag/today
          build: git-ci/ci
        get_params:
          skip_download: true

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: docker-image
    source:
      repository: cfcommunity/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: git
    type: git
    source:
      uri:         git@github.com:cloudfoundry/haproxy-boshrelease.git
      branch:      master
      private_key_user:    ((github.bot_user))
      private_key:         ((github.bot_deploy_key_private))

  - name: git-pull-requests
    type: pull-request
    source:
      access_token: ((github.access_token))
      repository:   cloudfoundry/haproxy-boshrelease
      base_branch:  master
      labels:       [run-ci]
      required_review_approvals: 1
      trusted_teams:
        - "wg-app-runtime-platform-networking-approvers"
      trusted_users:
        - "dependabot"
        - "CFN-CI"

  - name: stemcell-bionic
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-bionic-go_agent

  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-jammy-go_agent

  - name: version
    type: semver
    source :
      driver:          gcs
      bucket:          haproxy-boshrelease
      key:             version-13
      json_key:        ((gcp.service_key))
      initial_version: "12.2.1"

  - name: notify
    type: slack-notification
    source:
      url: ((slack.webhook))

  - name: github-release
    type: github-release
    source:
      user:         cloudfoundry
      repository:   haproxy-boshrelease
      access_token: ((github.access_token))
      drafts:       true

  - name: blobstore
    type: gcs
    source:
      bucket:   haproxy-boshrelease
      json_key: ((gcp.service_key))
      regexp:   haproxy-([0-9\.+-]+).tgz

  - name: daily
    type: time
    source:
      start: 7:00 AM
      stop: 8:00 AM
      location: Europe/Berlin
      interval: 24h

  - name: docker-cpi-image
    type: docker-image
    source:
      repository: bosh/docker-cpi

  - name: git-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/haproxy-boshrelease.git
      branch: master
      paths:
        - ci/Dockerfile
        - ci/scripts/requirements.txt

  - name: haproxy-boshrelease-testflight
    type: docker-image
    source:
      repository: europe-west3-docker.pkg.dev/app-runtime-platform-wg/arp-wg-docker/haproxy-boshrelease-testflight
      username: _json_key
      password: ((gcp.docker_image_writer_service_key))
